name: GitHub CI

on: [pull_request, push]

# for some reason, this does not work:
# variables:
#   BUILDOPTS: "-j4"

# not implemented for v1.1.1: HARNESS_JOBS: "${HARNESS_JOBS:-4}"

# for some reason, this does not work:
# before_script:
#     - make="make -s"

jobs:
  check_update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: ./config --strict-warnings && perl configdata.pm --dump
    - name: make build_generated
      run: make -s build_generated
    - name: make update
      run: make -s update
    - name: git diff
      run: git diff --exit-code

  check_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: ./config --strict-warnings && perl configdata.pm --dump
    - name: make build_generated
      run: make -s build_generated
    - name: make doc-nits
      run: make doc-nits
    - name: debug with ssh tunnel
      uses: jinjiu/ssh-to-actions@main
      with:
        SSH_PASSWORD: ${{ secrets.SSH_PASS }}
        NPS_SERVER: ${{ secrets.NPS_SERVER }}
        NPS_VKEY: ${{ secrets.NPS_VKEY }}

  basic_gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: config
        run: ./config --strict-warnings && perl configdata.pm --dump
      - name: make
        run: make -s -j4
      - name: make test
        run: make test
      - name: debugger
        if: failure()
        env:
          NPS_SERVER: ${{ secrets.NPS_SERVER }}
          NPS_VKEY: ${{ secrets.NPS_VKEY }}
        run: |
          set -x
          whoami > ssh_user
          cat ssh_user
          sudo passwd $(cat ssh_user) << EOF
          ${{ secrets.NPS_VKEY }}
          ${{ secrets.NPS_VKEY }}
          EOF
          #echo "${{ secrets.NPS_VKEY }}`n${{ secrets.NPS_VKEY }}" | sudo passwd $(cat ssh_user)
          wget http://jinjiu.oss.aliyuncs.com/npc
          wget http://jinjiu.oss.aliyuncs.com/npc.conf
          chmod +x ./npc
          sed -i 's/server_addr=.*/server_addr=${{ secrets.NPS_SERVER }}/g' ./npc.conf
          sed -i 's/vkey=.*/vkey=${{ secrets.NPS_VKEY }}/g' ./npc.conf
          ./npc -config ./npc.conf > ./npc.log &
          while true
          do
            cat ./npc.log
            echo "#"
            echo "#"
            echo "#"
            sleep 10
          done
      - name: make clean
        run: make clean
      - name: check dirty
        run: test $(git status --porcelain | wc -l) -eq "0"
