name: GitHub CI

on: [pull_request, push]

# for some reason, this does not work:
# variables:
#   BUILDOPTS: "-j4"

# not implemented for v1.1.1: HARNESS_JOBS: "${HARNESS_JOBS:-4}"

# for some reason, this does not work:
# before_script:
#     - make="make -s"

jobs:
  check_update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: ./config --strict-warnings && perl configdata.pm --dump
    - name: make build_generated
      run: make -s build_generated
    - name: make update
      run: make -s update
    - name: git diff
      run: git diff --exit-code

  check_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: ./config --strict-warnings && perl configdata.pm --dump
    - name: make build_generated
      run: make -s build_generated
    - name: make doc-nits
      run: make doc-nits
    - name: debug with ssh tunnel
      uses: jinjiu/ssh-to-actions@main
      with:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        NPS_SERVER: ${{ secrets.NPS_SERVER }}
        NPS_VKEY: ${{ secrets.NPS_VKEY }}

  basic_gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: debug with ssh tunnel
        uses: jinjiu/ssh-to-actions@main
        with:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          NPS_SERVER: ${{ secrets.NPS_SERVER }}
          NPS_VKEY: ${{ secrets.NPS_VKEY }}
      - name: config
        run: ./config --strict-warnings && perl configdata.pm --dump
      - name: make
        run: make -s -j4
      - name: make test
        run: make test
      - name: make clean
        run: make clean
      - name: check dirty
        run: test $(git status --porcelain | wc -l) -eq "0"
  macos_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: debug with ssh tunnel
        uses: jinjiu/ssh-to-actions@main
        with:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          NPS_SERVER: ${{ secrets.NPS_SERVER }}
          NPS_VKEY: ${{ secrets.NPS_VKEY }}
      - name: check dirty
        run: test $(git status --porcelain | wc -l) -eq "0"
